name: Chip8_Emu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: MinSizeRel

jobs:
  Windows:
    runs-on: windows-latest
    name: Windows latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
        submodules: recursive

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Setup vs prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: bin-win64-${{matrix.compiler}}.MinSizeRel
        path: |
          ${{github.workspace}}\build\CHIP8_Emu\MinSizeRel\CHIP8_Emu.exe

  Linux:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        compiler: ['clang', 'gcc']

    name: Ubuntu 20.04 / ${{matrix.compiler}}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
        submodules: recursive

    - name: Installing dependencies
      run: |
        sudo apt-get -y update
        sudo apt install -y g++-10 gcc-10 clang-11

    - name: Configure CMake with gcc
      if: matrix.compiler == 'gcc'
      env:
        CC: gcc-10
        CXX: g++-10
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Configure CMake with clang
      if: matrix.compiler == 'clang'
      env:
        CC: clang-11
        CXX: clang++-11
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: bin-linux64-${{matrix.compiler}}.MinSizeRel
        path: |
          ${{github.workspace}}/build/CHIP8_Emu/CHIP8_Emu
